const MetaApi = require('metaapi.cloud-sdk').default;

// Configuration for MetaApi
const metaApiToken = process.env.METAAPI_TOKEN || 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxYTkzNGM5MmY3NDRjNDgzMDliMmE1MWEyMjEyYTEzMyIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiMWE5MzRjOTJmNzQ0YzQ4MzA5YjJhNTFhMjIxMmExMzMiLCJpYXQiOjE3NDYyNTUwNzksImV4cCI6MTc1NDAzMTA3OX0.lyqFY-mwwh06CmwFtjNZTdrcVCf33o3gKuYKDUuq47fxouOy8-IjIUGox0MVc4Aact3wmkCtQzHPRMXjFkHs6PAIlqkQFmNA9AVpzbYb_XWBQIlqjK8h_WFLVDFF16CRWSQ0_0glx7ZzqBBj2ODGIN-L7u8qNSoz_Po_X8TlhzLGpzeSujGyoE-QLG-vrARY6VYETt2-GYkh--5fYzapXXrX5R_FgJupvqgMWWgm2IEV2C7xVYRQrauOD8LRGJEkYS8x7LxDJvXttiSBio3tCspEWU5uHee7lfwQq-w2DUa1f-dkNUc0Q7GH19UsMaECFDDvDkf_BuTJdggxC0913xIhpmY6HfJd6MAe7uEmRH1bTFSpqxZpUetHpRxcsUlqzodGlAX0LOmm4ydMrW8OVlHU1Yj2tdvbB8pVokS41TGTKhsKEDCMOMEDR3mgW3hy4ubthcBhP3nAMnktsOiPyiItbzjCPICmLcjoKxRj5mxCkf_zfX4sKUKYJAeNHzbwGw53CWAvRWtqzv7ys6JGfBFMfYK_objlXvCtU87HWnDHvqnte37F9A9oEP8_Vk4WG4SrQEA-SRYvupljnlIt6ANM9CcUp8ZhC8cWfFg9LEseamciruRw6qjmVidoHXzEy33y70ka_skI3UOLKtVb7BSm6QMRCQpal7G3eAzUQAY';
const metaApi = new MetaApi(metaApiToken);

// Default connection options
const connectionOptions = {
  application: 'TradingViewCRM',
  reconnect: true,
  timeout: 5000
};

module.exports = {
  metaApi,
  connectionOptions
};


